from .curriculum import ZONES_CURRICULUM, LETTER_CURRICULUM, FLATWORLD_CURRICULUM, FLATWORD_PRETRAINING, \
    CHESSWORLD_CURRICULUM, CHESSWORLD_PRETRAINING, CHESSWORLD8_CURRICULUM, CHESSWORLD8_PRETRAINING, \
    CHESSWORLD8EASY_CURRICULUM, CHESSWORLD8EASY_PRETRAINING, CHESSWORLD8_STAY_CURRICULUM, CHESSWORLD8_STAY_PRETRAINING, \
    CHESSWORLD8_SMALL_STAY, CHESSWORLD8_STAY_CURRICULUM_PROG, CHESSWORLD8_FORMULA_CURRICULUM, \
    PRETRAINING_CHESSWORLD8_FORMULA, CHESSWORLD8_PRETRAINING_TRANSFORMER, FLATWORLD_STAY_CURRICULUM, \
    FLATWORLD_FORMULA_CURRICULUM, PRETRAINING_FLATWORLD_FORMULA, FLATWORLD_FORMULA_UPDATE, \
    PRETRAINING_FLATWORLD_FORMULA_UPDATE, CHESSWORLD8_FORMULA_UPDATE, PRETRAINING_CHESSWORLD8_FORMULA_UPDATE, \
    RACING_FORMULA_CHESSWORLD8, RACING_FORMULA_CHESSWORLD8_UPDATE, ZONES_UPDATE_CURRICULUM, \
    ZONES_UPDATE_PRETRAINING_CURRICULUM
from .curriculum_sampler import CurriculumSampler

curricula = {
    'PointLtl2-v0': ZONES_CURRICULUM,
    'LetterEnv-v0': LETTER_CURRICULUM,
    'FlatWorld-v0': FLATWORLD_CURRICULUM,
    'pretraining_FlatWorld-v0': FLATWORD_PRETRAINING,
    'ChessWorld-v0': CHESSWORLD_CURRICULUM,
    'pretraining_ChessWorld-v0': CHESSWORLD_PRETRAINING,
    'ChessWorld-v1': CHESSWORLD8_CURRICULUM,
    'pretraining_ChessWorld-v1': CHESSWORLD8_PRETRAINING,
    'ChessWorld-v2': CHESSWORLD8EASY_CURRICULUM,
    'pretraining_ChessWorld-v2': CHESSWORLD8EASY_PRETRAINING,
    'stay_ChessWorld-v1': CHESSWORLD8_STAY_CURRICULUM,
    'pretraining_stay_ChessWorld-v1': CHESSWORLD8_STAY_PRETRAINING,
    'final_stay_ChessWorld-v1': CHESSWORLD8_SMALL_STAY,
    "prog_stay_ChessWorld-v1": CHESSWORLD8_STAY_CURRICULUM_PROG,
    "formula_ChessWorld-v1": CHESSWORLD8_FORMULA_CURRICULUM,
    'pretraining_formula_ChessWorld-v1': PRETRAINING_CHESSWORLD8_FORMULA,
    'pretraining_transformer_ChessWorld-v1': CHESSWORLD8_PRETRAINING_TRANSFORMER,
    'stay_FlatWorld-v0': FLATWORLD_STAY_CURRICULUM,
    'formula_FLatWorld-v0': FLATWORLD_FORMULA_CURRICULUM,
    'pretraining_formula_FlatWorld-v0': PRETRAINING_FLATWORLD_FORMULA,
    'update_FlatWorld-v0': FLATWORLD_FORMULA_UPDATE,
    'pretraining_update_FlatWorld-v0': PRETRAINING_FLATWORLD_FORMULA_UPDATE,
    'update_ChessWorld-v1': CHESSWORLD8_FORMULA_UPDATE,
    'pretraining_update_ChessWorld-v1': PRETRAINING_CHESSWORLD8_FORMULA_UPDATE,
    'racing_formula_ChessWorld-v1': RACING_FORMULA_CHESSWORLD8,
    'racing_formula_update_ChessWorld-v1': RACING_FORMULA_CHESSWORLD8_UPDATE,
    'update_PointLtl2-v0': ZONES_UPDATE_CURRICULUM,
    'pretraining_update_PointLtl2-v0': ZONES_UPDATE_PRETRAINING_CURRICULUM
}
