from .curriculum import ZONES_CURRICULUM, LETTER_CURRICULUM, FLATWORLD_CURRICULUM, FLATWORD_PRETRAINING, \
    CHESSWORLD_CURRICULUM, CHESSWORLD_PRETRAINING, CHESSWORLD8_CURRICULUM, CHESSWORLD8_PRETRAINING, \
    CHESSWORLD8EASY_CURRICULUM, CHESSWORLD8EASY_PRETRAINING
from .curriculum_sampler import CurriculumSampler

curricula = {
    'PointLtl2-v0': ZONES_CURRICULUM,
    'LetterEnv-v0': LETTER_CURRICULUM,
    'FlatWorld-v0': FLATWORLD_CURRICULUM,
    'pretraining_FlatWorld-v0': FLATWORD_PRETRAINING,
    'ChessWorld-v0': CHESSWORLD_CURRICULUM,
    'pretraining_ChessWorld-v0': CHESSWORLD_PRETRAINING,
    'ChessWorld-v1': CHESSWORLD8_CURRICULUM,
    'pretraining_ChessWorld-v1': CHESSWORLD8_PRETRAINING,
    'ChessWorld-v2': CHESSWORLD8EASY_CURRICULUM,
    'pretraining_ChessWorld-v2': CHESSWORLD8EASY_PRETRAINING
}
